apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name:  django-clearsessions-cron-job
    app.kubernetes.io/instance: django-clearsessions-cron-job
    app.kubernetes.io/version: 3.2.2
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: django-application-k8s-example
    app.kubernetes.io/managed-by: kubectl
  name: django-clearsessions-cron-jobs
spec:
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Forbid 
  schedule: "* * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
          - name: clear-sessions
            image: corwinz/dj:82bdd63
            ports:
            - containerPort: 80
            envFrom:
              - secretRef:
                  name: django-secret-v1
              - configMapRef:
                  name: django-configmap-v1
            resources:
              limits:
                memory: 256Mi
                cpu: "0.5"
              requests:
                memory: 128Mi
                cpu: "0.1"
            command:
            - "pthon"
            args: 
            - "manage.py"
            - "clearsessions"
          restartPolicy: Never
