apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: django-migrate
    app.kubernetes.io/instance: django-migrate
    app.kubernetes.io/version: 3.2.2
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: django-application-k8s-example
    app.kubernetes.io/managed-by: kubectl
  name: django-migrate
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 360
  template:
    spec:
      containers:
      - name: django-migrate
        image: corwinz/dj:82bdd63
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: django-secret-v1
          - configMapRef:
              name: django-configmap-v1
        resources:
          limits:
            memory: 256Mi
            cpu: "0.5"
          requests:
            memory: 128Mi
            cpu: "0.1"
        command:
        - "python"
        args: 
        - "manage.py"
        - "migrate"
        - "--noinput"
      restartPolicy: Never
