apiVersion: v1
kind: Pod
metadata:
  name: clear-sessions
spec:
  containers:
  - name: django-unit
    image: dj:fresh
    command: ["python"]
    args: ["manage.py", "clearsessions"]
    envFrom:
      - configMapRef:
          name: django-configmap-v4
  restartPolicy: OnFailure
