apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: django-migrate
    app.kubernetes.io/instance: django-migrate
    app.kubernetes.io/version: 3.2.2
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: django-application-k8s-example
    app.kubernetes.io/managed-by: kubectl
  name: django-migrate
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 360
  template:
    spec:
      containers:
      - name: django-migrate
        image: dj:fresh
        command:
        - "python"
        args: 
        - "manage.py"
        - "migrate"
        - "--noinput"
        envFrom:
          - configMapRef:
              name: django-configmap-v1
      restartPolicy: Never
